### ISSUE TITLE
MissingPositionPanel does not show map / HTTP 503 for WMS

### ISSUE THREAD

**Issue by johnjohndoe** [52North/sos-importer#32]
When I run the importer (built from source 99469b6283fe458a8843aed66ea98c10303362f1) there is no map shown in the "Add missing position" step as shown in the screenshot.

![add-missing-position](https://cloud.githubusercontent.com/assets/144518/6506557/51612aa0-c34c-11e4-8320-38f7ddfaf81a.png)

The console output reveals that the WMS backend is not reachable:

```
15:26:03.881 [AWT-EventQueue-0] DEBUG Constants - WMS url: 
    'http://129.206.228.72/cached/osm'
15:26:35.207 [AWT-EventQueue-0] ERROR MissingPositionPanel - Exception thrown: 
    Server returned HTTP response code: 503 for URL: 
    http://129.206.228.72/cached/osm?REQUEST=GetCapabilities&VERSION=1.1.0&SERVICE=WMS
java.io.IOException: Server returned HTTP response code: 503 for URL: 
    http://129.206.228.72/cached/osm?REQUEST=GetCapabilities&VERSION=1.1.0&SERVICE=WMS

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1838) ~[na:1.8.0_40-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439) ~[na:1.8.0_40-internal]
	at org.geotools.data.ows.SimpleHttpClient$SimpleHTTPResponse.<init>(SimpleHttpClient.java:170) ~[52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.geotools.data.ows.SimpleHttpClient.get(SimpleHttpClient.java:102) ~[52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.geotools.data.ows.AbstractOpenWebService.internalIssueRequest(AbstractOpenWebService.java:424) ~[52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.geotools.data.wms.WebMapServer.issueRequest(WebMapServer.java:419) ~[52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.geotools.data.ows.AbstractOpenWebService.negotiateVersion(AbstractOpenWebService.java:260) ~[52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:110) ~[52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:75) ~[52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.geotools.data.wms.WebMapServer.<init>(WebMapServer.java:370) ~[52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.n52.sos.importer.view.position.MissingPositionPanel.initMap(MissingPositionPanel.java:246) [52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.n52.sos.importer.view.position.MissingPositionPanel.initMapPanel(MissingPositionPanel.java:139) [52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.n52.sos.importer.view.position.MissingPositionPanel.<init>(MissingPositionPanel.java:109) [52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.n52.sos.importer.view.Step6cPanel.<init>(Step6cPanel.java:63) [52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.n52.sos.importer.controller.Step6cController.loadSettings(Step6cController.java:76) [52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.n52.sos.importer.controller.MainController.setStepController(MainController.java:81) [52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.n52.sos.importer.controller.BackNextController.nextButtonClicked(BackNextController.java:131) [52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
	at org.n52.sos.importer.view.BackNextPanel$NextButtonClicked.actionPerformed(BackNextPanel.java:130) [52n-sos-importer-core-0.4.0-SNAPSHOT-bin.jar:0.4.0-SNAPSHOT]
        ...
```

**Comment by EHJ-52n** [comment]
WMS panel could not be supported because of bad license of transitive dependencies of gt-swing and others.
