### ISSUE TITLE
Import logs: Sending request failed caused by SocketTimeoutException

### ISSUE THREAD

**Issue by johnjohndoe** [52North/sos-importer#51]
Each time I run the importer the following is output to the console:

``` java
[org.n52.sos.importer.feeder.task.OneTimeFeeder] ERROR SensorObservationService - 
  Insert observation failed for sensor '10'[10]. Store: TimeSeries [sensor=10, observedProperty=ObservedProperty 
  [name=Partikel, PM10, Tagesmittel, uri=Partikel_PM10_Tagesmittel], 
  feature=http://www.stadtentwicklung.berlin.de/umwelt/umweltatlas/extra/3_12/d312_MC010.htm]
[org.n52.sos.importer.feeder.task.OneTimeFeeder] DEBUG SimpleHttpClient - 
  executing POST method to 'http://localhost:8080/52n-sos-webapp/service/pox'.
[org.n52.sos.importer.feeder.task.OneTimeFeeder] ERROR SensorObservationService - 
  Problem with OXF. Exception thrown: Sending request failed.
org.n52.oxf.OXFException: Sending request failed.

	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:392) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:437) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.oxf.sos.adapter.wrapper.SOSWrapper.doInsertObservation(SOSWrapper.java:319) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.sos.importer.feeder.SensorObservationService.insertSweArrayObservation(SensorObservationService.java:755) [52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.sos.importer.feeder.SensorObservationService.insertTimeSeries(SensorObservationService.java:652) [52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.sos.importer.feeder.SensorObservationService.importData(SensorObservationService.java:376) [52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.sos.importer.feeder.task.OneTimeFeeder.run(OneTimeFeeder.java:203) [52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

Caused by: org.n52.oxf.util.web.HttpClientException: Could not execute request.
	at org.n52.oxf.util.web.SimpleHttpClient.executeMethod(SimpleHttpClient.java:169) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.oxf.util.web.SimpleHttpClient.executePost(SimpleHttpClient.java:161) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.oxf.util.web.SimpleHttpClient.executePost(SimpleHttpClient.java:154) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.oxf.util.web.HttpClientDecorator.executePost(HttpClientDecorator.java:68) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.oxf.util.web.HttpClientDecorator.executePost(HttpClientDecorator.java:68) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:366) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	... 7 common frames omitted

Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.7.0_79]
	at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[na:1.7.0_79]
	at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[na:1.7.0_79]
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:166) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	....
	at org.n52.oxf.util.web.SimpleHttpClient.executeMethod(SimpleHttpClient.java:166) ~[52n-sos-importer-feeder-bin.jar:0.5.0-SNAPSHOT]
	... 12 common frames omitted
```
This messages are very **misleading** until I realized that all data is imported **successfully** nonetheless.

### Steps to reproduce

Please use the following files to reproduce the case:

* [sensordata-010-without-count.csv.52n-sos-import-config.xml](https://dl.dropboxusercontent.com/u/2071482/SOS-SocketTimeoutException/sensordata-010-without-count.csv.52n-sos-import-config.xml)
* [sensordata-010-without-count-single-line.csv](https://dl.dropboxusercontent.com/u/2071482/SOS-SocketTimeoutException/sensordata-010-without-count-single-line.csv)

Here you find the server log and the console output of the importer.

* [52n-sos-webapp-single-line.log](https://dl.dropboxusercontent.com/u/2071482/SOS-SocketTimeoutException/52n-sos-webapp-single-line.log)
* [sensordata-010-without-count-single-line.log](https://dl.dropboxusercontent.com/u/2071482/SOS-SocketTimeoutException/sensordata-010-without-count-single-line.log)

---

### Related

* [Issue #44: Import fails with SocketTimeoutException (through duplicate key value) or ExceptionReport: null](https://github.com/52North/sos-importer/issues/44)

---

/cc @CarstenHollmann

**Comment by johnjohndoe** [comment]
@CarstenHollmann Any progress on this issue?

**Comment by CarstenHollmann** [comment]
I think there were so far no resources available  to look at this issue more closely. 

The settings you mentioned are the database connection settings of the SOS which defines the maximum number of database connection and the batch size defines after how many observation (if multiple observations are inserted by a single InsertObservation request) a flush() is executed.

As far as I know the SOS-Importer executes the requests successively. Therefore, the settings should be insignificant for this issue.

But perhaps @EHJ-52n can say more about the progress.

**Comment by EHJ-52n** [comment]
@johnjohndoe The error message is caused by the SOS taking too long for handling the received insert observation message. The SOS receives the whole message successfully but takes to long to process and therefore the read timeout of the http client is reached and the exception is thrown. To get rid of it, you can increase/add the attribute ```insertSweArrayObservationTimeoutBuffer="50000"``` to the ```<SosMetadata>``` element. This will result in a longer timeout for each insert observation request. Take a look at the [documentation](https://github.com/52North/sos-importer/blob/988025b178e840e73ce2aa0f3e84ca8fc96c9190/bindings/src/main/resources/import-configuration.xsd#L1171) for more details.

**Comment by johnjohndoe** [comment]
@EHJ-52n That works like a charm. Thank you!
