### ISSUE TITLE
NullPointerException when parsing Date/Time

### ISSUE THREAD

**Issue by BWibo** [52North/sos-importer#78]
I am facing some issues when trying to import data from a csv file related to parsing different datetime formats. I tried both release [0.4.0](https://github.com/52North/sos-importer/releases/tag/52n-sos-importer-0.4.0) and a fresh build I created from [develop/abdbd0ad](https://github.com/52North/sos-importer/commit/abdbd0ad9be3bcafe42d981361e3025abdb668b2).

The SOS I am trying to import to is [v4.4.0](https://github.com/52North/SOS/releases/tag/v4.4.0).

The import works fine with both versions for the following file and configuration:
#### CSV
```
datetime;temp;humidity
2017-04-13T08:27:28;20.80;39.20
2017-04-13T08:28:05;20.70;39.10
2017-04-13T08:28:36;20.70;39.10
2017-04-13T08:29:06;20.70;39.10
2017-04-13T08:29:37;20.70;39.10
````
#### Feeder config
```xml
<!-- ... -->
<CsvMetadata>
    <ColumnAssignments>
        <Column>
            <Number>0</Number>
            <Type>DATE_TIME</Type>
            <Metadata>
                <Key>GROUP</Key>
                <Value>1</Value>
            </Metadata>
            <Metadata>
                <Key>PARSE_PATTERN</Key>
                <Value>yyyy-MM-dd'T'HH:mm:ss</Value>
            </Metadata>
            <Metadata>
                <Key>TYPE</Key>
                <Value>COMBINATION</Value>
            </Metadata>
            <Metadata>
                <Key>TIME_ZONE</Key>
                <Value>0</Value>
            </Metadata>
        </Column>
<!-- ... -->
```

For the following combination, however, both versions produce an exception.
For the given example, the wizard of both versions tells me that _all values could be interpreted_, but, the feeder module produces an exception, when trying to import the data.

Am I missing something here, or is this a bug?

#### CSV
```
datetime;temp;humidity
2017-04-13T08:27:28Z;20.80;39.20
2017-04-13T08:28:05Z;20.70;39.10
2017-04-13T08:28:36Z;20.70;39.10
2017-04-13T08:29:06Z;20.70;39.10
2017-04-13T08:29:37Z;20.70;39.10
2017-04-13T08:30:07Z;20.70;39.10
```
#### Feeder config
```xml
<!-- ... -->
<CsvMetadata>
    <ColumnAssignments>
        <Column>
            <Number>0</Number>
            <Type>DATE_TIME</Type>
            <Metadata>
                <Key>GROUP</Key>
                <Value>1</Value>
            </Metadata>
            <Metadata>
                <Key>PARSE_PATTERN</Key>
                <Value>yyyy-MM-dd'T'HH:mm:ss'Z'</Value>
            </Metadata>
            <Metadata>
                <Key>TYPE</Key>
                <Value>COMBINATION</Value>
            </Metadata>
        </Column>
<!-- ... -->
```

##### Exception version 0.4.0
```
18:23:50.832 [OneTimeFeeder] TRACE SensorObservationService - importData()
18:23:50.848 [OneTimeFeeder] DEBUG SensorObservationService - Using hunkSize '5000'
18:23:50.848 [OneTimeFeeder] DEBUG SensorObservationService - Handling CSV line #2: [2017-04-13T08:27:28Z, 20.80, 39.20]
18:23:50.848 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 1
18:23:50.848 [OneTimeFeeder] DEBUG SensorObservationService - Sensor: Sensor [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
18:23:50.864 [OneTimeFeeder] DEBUG SensorObservationService - Feature of Interest: FeatureOfInterest [p=Position [values=[11.549077033996582, 48.100852966308594, 525.0], units=[deg, deg, meters], epsgCode=4326], name=foi-group99, uri=urn:foi:group99]
18:23:50.864 [OneTimeFeeder] DEBUG SensorObservationService - Value: 20.8
18:23:50.864 [OneTimeFeeder] DEBUG SensorObservationService - Timestamp: 2017-04-13T08:27:28
18:23:50.864 [OneTimeFeeder] DEBUG SensorObservationService - UomCode: 'UnitOfMeasurement [name=degC, uri=urn:ucum:temperature:celsius]'
18:23:50.879 [OneTimeFeeder] DEBUG SensorObservationService - ObservedProperty: ObservedProperty [name=temperature, uri=temperature]
18:23:50.879 [OneTimeFeeder] DEBUG SensorObservationService - Offering: Offering [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
18:23:50.879 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 2
18:23:50.879 [OneTimeFeeder] DEBUG SensorObservationService - Sensor: Sensor [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
18:23:50.879 [OneTimeFeeder] DEBUG SensorObservationService - Feature of Interest: FeatureOfInterest [p=Position [values=[11.549077033996582, 48.100852966308594, 525.0], units=[deg, deg, meters], epsgCode=4326], name=foi-group99, uri=urn:foi:group99]
18:23:50.879 [OneTimeFeeder] DEBUG SensorObservationService - Value: 39.2
18:23:50.879 [OneTimeFeeder] DEBUG SensorObservationService - Timestamp: 2017-04-13T08:27:28

...
...

18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - Timestamp: 2017-04-13T08:45:27
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - UomCode: 'UnitOfMeasurement [name=degC, uri=urn:ucum:temperature:celsius]'
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - ObservedProperty: ObservedProperty [name=temperature, uri=temperature]
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - Offering: Offering [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 2
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - Sensor: Sensor [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - Feature of Interest: FeatureOfInterest [p=Position [values=[11.549077033996582, 48.100852966308594, 525.0], units=[deg, deg, meters], epsgCode=4326], name=foi-group99, uri=urn:foi:group99]
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - Value: 39.1
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - Timestamp: 2017-04-13T08:45:27
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - UomCode: 'UnitOfMeasurement [name=%, uri=urn:ucum:percent]'
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - ObservedProperty: ObservedProperty [name=humidity, uri=urn:humidity]
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - Offering: Offering [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
18:23:51.176 [OneTimeFeeder] DEBUG SensorObservationService - HeapSize Information: max: 7282MB; total now: 491MB; free now: 426MB; used now: 64MB
18:23:51.176 [OneTimeFeeder] TRACE SensorObservationService - insertTimeSeries()
18:23:51.442 [OneTimeFeeder] DEBUG SimpleHttpClient - executing POST method to 'http://xxx/service/pox'.
18:23:51.740 [OneTimeFeeder] DEBUG SensorObservationService - InsertSensorResponse parsed
18:23:51.743 [OneTimeFeeder] INFO  SensorObservationService - Sensor registered at SOS  'http://xxx/service' with assigned id 'http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/'
Exception in thread "OneTimeFeeder" java.lang.NullPointerException
	at org.n52.oxf.valueDomains.time.TimePosition.toISO8601Format(TimePosition.java:447)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder200POX.addResultTimeObject(SOSRequestBuilder200POX.java:608)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder200POX.addResultTime(SOSRequestBuilder200POX.java:588)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder200POX.addObservations(SOSRequestBuilder200POX.java:334)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder200POX.buildInsertObservationRequest(SOSRequestBuilder200POX.java:290)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder_200.buildInsertObservationRequest(SOSRequestBuilder_200.java:111)
	at org.n52.oxf.sos.adapter.SOSAdapter.buildRequest(SOSAdapter.java:499)
	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:313)
	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:437)
	at org.n52.oxf.sos.adapter.wrapper.SOSWrapper.doInsertObservation(SOSWrapper.java:319)
	at org.n52.sos.importer.feeder.SensorObservationService.insertSweArrayObservation(SensorObservationService.java:746)
	at org.n52.sos.importer.feeder.SensorObservationService.insertTimeSeries(SensorObservationService.java:643)
	at org.n52.sos.importer.feeder.SensorObservationService.importData(SensorObservationService.java:376)
	at org.n52.sos.importer.feeder.task.OneTimeFeeder.run(OneTimeFeeder.java:203)
	at java.lang.Thread.run(Unknown Source)
```

##### Exception develop/abdbd0ad
```
18:19:57.847 [OneTimeFeeder] DEBUG FileHelper - Shortened String 'D_pi_importer_config_Z_pi01-dht22-Z.xml_D_pi_importer_config_Z_dht22-small-Z.csv_counter' to '0eec5bc0932069768bca7cdcf9461d86'
18:19:57.847 [OneTimeFeeder] DEBUG OneTimeFeeder - Check counter file 'C:\Users\bruno\.SOSImporter\0eec5bc0932069768bca7cdcf9461d86'.
18:19:57.847 [OneTimeFeeder] DEBUG OneTimeFeeder - Counter file does not exist.
18:19:57.847 [OneTimeFeeder] TRACE SensorObservationService - importData()
18:19:57.847 [OneTimeFeeder] DEBUG SensorObservationService - Using hunkSize '5000'
18:19:57.863 [OneTimeFeeder] DEBUG SensorObservationService - Handling CSV line #2: [2017-04-13T08:27:28Z, 20.80, 39.20]
18:19:57.863 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 1
18:19:57.863 [OneTimeFeeder] DEBUG SensorObservationService - Sensor: Sensor [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
18:19:57.894 [OneTimeFeeder] DEBUG SensorObservationService - Feature of Interest: FeatureOfInterest [p=Position [values=[11.549077033996582, 48.100852966308594, 525.0], units=[deg, deg, meters], epsgCode=4326], name=foi-group99, uri=urn:foi:group99]
18:19:57.894 [OneTimeFeeder] DEBUG SensorObservationService - Value: 20.8
18:19:57.894 [OneTimeFeeder] ERROR SensorObservationService - Could not retrieve all information required for insert observation because of parsing error: java.text.ParseException: Unparseable date: "2017-04-13T08:27:28+0100". Skipped this one.
18:19:57.894 [OneTimeFeeder] DEBUG SensorObservationService - Exception stack trace:
java.text.ParseException: Unparseable date: "2017-04-13T08:27:28+0100"
	at java.text.DateFormat.parse(Unknown Source)
	at org.n52.sos.importer.feeder.DataFile.parseTimestampComponent(DataFile.java:976)
	at org.n52.sos.importer.feeder.DataFile.handleDateTimeCombination(DataFile.java:508)
	at org.n52.sos.importer.feeder.DataFile.getTimeStamp(DataFile.java:481)
	at org.n52.sos.importer.feeder.SensorObservationService.getInsertObservationForColumnIdFromValues(SensorObservationService.java:688)
	at org.n52.sos.importer.feeder.SensorObservationService.getInsertObservations(SensorObservationService.java:659)
	at org.n52.sos.importer.feeder.SensorObservationService.importData(SensorObservationService.java:368)
	at org.n52.sos.importer.feeder.task.OneTimeFeeder.run(OneTimeFeeder.java:228)
	at java.lang.Thread.run(Unknown Source)
18:19:57.894 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 2
```

**Comment by EHJ-52n** [comment]
Dear @BWibo,
thank you very much for your detailed report. I hope to be able for taking a look today or tomorrow.
Kind regards!

**Comment by BWibo** [comment]
I just found out that the same applies for this example. The wizard tells me _all values could be interpreted_ but the feeder fails to import.

#### CSV
```
datetime;temp;humidity
2017-04-13T08:27:28MESZ;20.80;39.20
2017-04-13T08:28:05MESZ;20.70;39.10
2017-04-13T08:28:36MESZ;20.70;39.10
2017-04-13T08:29:06MESZ;20.70;39.10
2017-04-13T08:29:37MESZ;20.70;39.10
```

#### Feeder config
```xml
<!-- ... -->
<CsvMetadata>
    <ColumnAssignments>
        <Column>
            <Number>0</Number>
            <Type>DATE_TIME</Type>
            <Metadata>
                <Key>GROUP</Key>
                <Value>1</Value>
            </Metadata>
            <Metadata>
                <Key>PARSE_PATTERN</Key>
                <Value>yyyy-MM-dd'T'HH:mm:ssz</Value>
            </Metadata>
            <Metadata>
                <Key>TYPE</Key>
                <Value>COMBINATION</Value>
            </Metadata>
        </Column>
<!-- ... -->
```

##### Exception v 0.4.0
```
15:43:07.756 [OneTimeFeeder] DEBUG SensorObservationService - Handling CSV line #37: [2017-04-13T08:45:27MESZ, 20.60, 39.10]
15:43:07.756 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 1
15:43:07.756 [OneTimeFeeder] DEBUG SensorObservationService - Sensor: Sensor [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
15:43:07.757 [OneTimeFeeder] DEBUG SensorObservationService - Feature of Interest: FeatureOfInterest [p=Position [values=[11.549077033996582, 48.100852966308594, 525.0], units=[deg, deg, meters], epsgCode=4326], name=foi-group99, uri=urn:foi:group99]
15:43:07.757 [OneTimeFeeder] DEBUG SensorObservationService - Value: 20.6
15:43:07.758 [OneTimeFeeder] DEBUG SensorObservationService - Timestamp: 2017-04-13T08:45:27
15:43:07.758 [OneTimeFeeder] DEBUG SensorObservationService - UomCode: 'UnitOfMeasurement [name=degC, uri=urn:ucum:temperature:celsius]'
15:43:07.758 [OneTimeFeeder] DEBUG SensorObservationService - ObservedProperty: ObservedProperty [name=temperature, uri=temperature]
15:43:07.759 [OneTimeFeeder] DEBUG SensorObservationService - Offering: Offering [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
15:43:07.759 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 2
15:43:07.759 [OneTimeFeeder] DEBUG SensorObservationService - Sensor: Sensor [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
15:43:07.760 [OneTimeFeeder] DEBUG SensorObservationService - Feature of Interest: FeatureOfInterest [p=Position [values=[11.549077033996582, 48.100852966308594, 525.0], units=[deg, deg, meters], epsgCode=4326], name=foi-group99, uri=urn:foi:group99]
15:43:07.760 [OneTimeFeeder] DEBUG SensorObservationService - Value: 39.1
15:43:07.761 [OneTimeFeeder] DEBUG SensorObservationService - Timestamp: 2017-04-13T08:45:27
15:43:07.761 [OneTimeFeeder] DEBUG SensorObservationService - UomCode: 'UnitOfMeasurement [name=%, uri=urn:ucum:percent]'
15:43:07.762 [OneTimeFeeder] DEBUG SensorObservationService - ObservedProperty: ObservedProperty [name=humidity, uri=urn:humidity]
15:43:07.762 [OneTimeFeeder] DEBUG SensorObservationService - Offering: Offering [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
15:43:07.762 [OneTimeFeeder] DEBUG SensorObservationService - HeapSize Information: max: 7282MB; total now: 491MB; free now: 424MB; used now: 66MB
15:43:07.762 [OneTimeFeeder] TRACE SensorObservationService - insertTimeSeries()
15:43:08.006 [OneTimeFeeder] DEBUG SimpleHttpClient - executing POST method to 'http://not.my.SOS/52n-sos-webapp/service/pox'.
15:43:08.415 [OneTimeFeeder] DEBUG SensorObservationService - InsertSensorResponse parsed
15:43:08.418 [OneTimeFeeder] INFO  SensorObservationService - Sensor registered at SOS  'http://not.my.SOS/52n-sos-webapp/service' with assigned id 'http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/'
Exception in thread "OneTimeFeeder" java.lang.NullPointerException
	at org.n52.oxf.valueDomains.time.TimePosition.toISO8601Format(TimePosition.java:447)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder200POX.addResultTimeObject(SOSRequestBuilder200POX.java:608)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder200POX.addResultTime(SOSRequestBuilder200POX.java:588)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder200POX.addObservations(SOSRequestBuilder200POX.java:334)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder200POX.buildInsertObservationRequest(SOSRequestBuilder200POX.java:290)
	at org.n52.oxf.sos.adapter.v200.SOSRequestBuilder_200.buildInsertObservationRequest(SOSRequestBuilder_200.java:111)
	at org.n52.oxf.sos.adapter.SOSAdapter.buildRequest(SOSAdapter.java:499)
	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:313)
	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:437)
	at org.n52.oxf.sos.adapter.wrapper.SOSWrapper.doInsertObservation(SOSWrapper.java:319)
	at org.n52.sos.importer.feeder.SensorObservationService.insertSweArrayObservation(SensorObservationService.java:746)
	at org.n52.sos.importer.feeder.SensorObservationService.insertTimeSeries(SensorObservationService.java:643)
	at org.n52.sos.importer.feeder.SensorObservationService.importData(SensorObservationService.java:376)
	at org.n52.sos.importer.feeder.task.OneTimeFeeder.run(OneTimeFeeder.java:203)
	at java.lang.Thread.run(Unknown Source)
```

##### develop/abdbd0ad

```
15:37:08.405 [OneTimeFeeder] TRACE SensorObservationService - importData()
15:37:08.421 [OneTimeFeeder] DEBUG SensorObservationService - Using hunkSize '5000'
15:37:08.421 [OneTimeFeeder] DEBUG SensorObservationService - Handling CSV line #2: [2017-04-13T08:27:28MESZ, 20.80, 39.20]
15:37:08.421 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 1
15:37:08.437 [OneTimeFeeder] DEBUG SensorObservationService - Sensor: Sensor [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
15:37:08.452 [OneTimeFeeder] DEBUG SensorObservationService - Feature of Interest: FeatureOfInterest [p=Position [values=[11.549077033996582, 48.100852966308594, 525.0], units=[deg, deg, meters], epsgCode=4326], name=foi-group99, uri=urn:foi:group99]
15:37:08.452 [OneTimeFeeder] DEBUG SensorObservationService - Value: 20.8
15:37:08.452 [OneTimeFeeder] ERROR SensorObservationService - Could not retrieve all information required for insert observation because of parsing error: java.text.ParseException: Unparseable date: "2017-04-13T08:27:28MES+0100". Skipped this one.
15:37:08.468 [OneTimeFeeder] DEBUG SensorObservationService - Exception stack trace:
java.text.ParseException: Unparseable date: "2017-04-13T08:27:28MES+0100"
	at java.text.DateFormat.parse(Unknown Source)
	at org.n52.sos.importer.feeder.DataFile.parseTimestampComponent(DataFile.java:976)
	at org.n52.sos.importer.feeder.DataFile.handleDateTimeCombination(DataFile.java:508)
	at org.n52.sos.importer.feeder.DataFile.getTimeStamp(DataFile.java:481)
	at org.n52.sos.importer.feeder.SensorObservationService.getInsertObservationForColumnIdFromValues(SensorObservationService.java:688)
	at org.n52.sos.importer.feeder.SensorObservationService.getInsertObservations(SensorObservationService.java:659)
	at org.n52.sos.importer.feeder.SensorObservationService.importData(SensorObservationService.java:368)
	at org.n52.sos.importer.feeder.task.OneTimeFeeder.run(OneTimeFeeder.java:228)
	at java.lang.Thread.run(Unknown Source)
15:37:08.468 [OneTimeFeeder] DEBUG SensorObservationService - Parsing measured value column 2
15:37:08.468 [OneTimeFeeder] DEBUG SensorObservationService - Sensor: Sensor [name=dht-22, uri=http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/]
15:37:08.468 [OneTimeFeeder] DEBUG SensorObservationService - Feature of Interest: FeatureOfInterest [p=Position [values=[11.549077033996582, 48.100852966308594, 525.0], units=[deg, deg, meters], epsgCode=4326], name=foi-group99, uri=urn:foi:group99]
15:37:08.468 [OneTimeFeeder] DEBUG SensorObservationService - Value: 39.2
15:37:08.468 [OneTimeFeeder] ERROR SensorObservationService - Could not retrieve all information required for insert observation because of parsing error: java.text.ParseException: Unparseable date: "2017-04-13T08:27:28MES+0100". Skipped this one.
15:37:08.468 [OneTimeFeeder] DEBUG SensorObservationService - Exception stack trace:
java.text.ParseException: Unparseable date: "2017-04-13T08:27:28MES+0100"
	at java.text.DateFormat.parse(Unknown Source)
	at org.n52.sos.importer.feeder.DataFile.parseTimestampComponent(DataFile.java:976)
	at org.n52.sos.importer.feeder.DataFile.handleDateTimeCombination(DataFile.java:508)
	at org.n52.sos.importer.feeder.DataFile.getTimeStamp(DataFile.java:481)
	at org.n52.sos.importer.feeder.SensorObservationService.getInsertObservationForColumnIdFromValues(SensorObservationService.java:688)
	at org.n52.sos.importer.feeder.SensorObservationService.getInsertObservations(SensorObservationService.java:659)
	at org.n52.sos.importer.feeder.SensorObservationService.importData(SensorObservationService.java:368)
	at org.n52.sos.importer.feeder.task.OneTimeFeeder.run(OneTimeFeeder.java:228)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by EHJ-52n** [comment]
@BWibo Supporting the `z` is not so easy to implement with the current version. I am working on this.

**Comment by EHJ-52n** [comment]
@BWibo 
The format `2017-04-13T08:27:28MESZ` is not supported with java 8 time api.

The supported output looks like

- `2017-04-13T08:27:28+02:00[Europe/Berlin]` for [ZonedDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html#parse-java.lang.CharSequence-) or 
- `2017-04-13T08:27:28+02:00` for [OffsetDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#parse-java.lang.CharSequence-).

Could you change the format in the outputting program?

**Comment by BWibo** [comment]
Yes, that's no problem.
