### ISSUE TITLE
Failed import of new sensor

### ISSUE THREAD

**Issue by cjsteele87** [52North/sos-importer#98]
Hello,

I'm trying to upload a very simple csv but I'm running into issues, specifically with importing a new sensor. The error states that the sensor could not be registered at SOS but I can't find any reason why.
 
The csv is very simple. It consists of a single observation made for a single sensor at a single point in time. Attached are my configuration, log and csv files that I have been using .

[SOSimporttest.tar.gz](https://github.com/52North/sos-importer/files/1833375/SOSimporttest.tar.gz)

any help would be very much appreciated.

**Comment by EHJ-52n** [comment]
Hi @cjsteele87!

1. Are you able to provide the logs of the SOS instance _after_ you changed the log level, so you can see the requests, the importer is sending?
1. Which SOS implementation are you using?
1. Would you be able to switch to the latest development version? If yes, you need to change the configuration a little bit. I can support you during this steps.

Kind regards.

**Comment by cjsteele87** [comment]
Thanks for your quick response @EHJ-52n.
Where can I change the log level? 
I'm using the latest release (v0.4.0) from the jar bundles, rather than a build from source. I attempted to build a seperate development version however, it fails to build, giving the error below...

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
[DEBUG] Setting system property [user.dir]=[/users/rsg/chs/Documents/SOSbuild/sos-importer/wizard]
[DEBUG] Setting system property [localRepository]=[/users/rsg/chs/.m2/repository]
[DEBUG] Setting system property [basedir]=[/users/rsg/chs/Documents/SOSbuild/sos-importer/wizard]
[DEBUG] Using JVM: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.fc24.x86_64/jre/bin/java
[DEBUG] test classpath classpath:
[DEBUG]   /users/rsg/chs/Documents/SOSbuild/sos-importer/wizard/target/test-classes
[DEBUG]   /users/rsg/chs/Documents/SOSbuild/sos-importer/wizard/target/classes
[DEBUG]   /users/rsg/chs/Documents/SOSbuild/sos-importer/bindings/target/52n-sos-importer-bindings-0.4.0.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-oxf-xmlbeans/2.0.0-alpha.4/52n-oxf-xmlbeans-2.0.0-alpha.4.jar
[DEBUG]   /users/rsg/chs/.m2/repository/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
[DEBUG]   /users/rsg/chs/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-gml-v321/1.1.5/52n-xml-gml-v321-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-xlink-v110/1.1.5/52n-xml-xlink-v110-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-soap-v12/1.1.5/52n-xml-soap-v12-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-swes-v20/1.1.5/52n-xml-swes-v20-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-ows-v110/1.1.5/52n-xml-ows-v110-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-wsa-v10/1.1.5/52n-xml-wsa-v10-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-wsn-v13/1.1.5/52n-xml-wsn-v13-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-wsrf-v12/1.1.5/52n-xml-wsrf-v12-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-sampling-v20/1.1.5/52n-xml-sampling-v20-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-om-v20/1.1.5/52n-xml-om-v20-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-sos-v20/1.1.5/52n-xml-sos-v20-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-filter-v20/1.1.5/52n-xml-filter-v20-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/52n-xml-sweCommon-v20/1.1.5/52n-xml-sweCommon-v20-1.1.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/n52/sensorweb/oxf-third-party-saxon/2.0.0-alpha.4/oxf-third-party-saxon-2.0.0-alpha.4.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/apache/xmlbeans/xmlbeans-xpath/2.6.0/xmlbeans-xpath-2.6.0.jar
[DEBUG]   /users/rsg/chs/.m2/repository/net/sf/saxon/Saxon-HE/9.4.0.6/Saxon-HE-9.4.0.6.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/junit/junit/4.10/junit-4.10.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar
[DEBUG]   /users/rsg/chs/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/apache/httpcomponents/httpclient/4.2.3/httpclient-4.2.3.jar
[DEBUG]   /users/rsg/chs/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/apache/httpcomponents/httpcore/4.2.3/httpcore-4.2.3.jar
[DEBUG]   /users/rsg/chs/.m2/repository/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/apache/xmlbeans/xmlbeans/2.5.0/xmlbeans-2.5.0.jar
[DEBUG]   /users/rsg/chs/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar
[DEBUG]   /users/rsg/chs/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar
[DEBUG]   /users/rsg/chs/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar
[DEBUG]   /users/rsg/chs/.m2/repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/geotools/gt-epsg-hsql/9.5/gt-epsg-hsql-9.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/geotools/gt-referencing/9.5/gt-referencing-9.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
[DEBUG]   /users/rsg/chs/.m2/repository/commons-pool/commons-pool/1.5.4/commons-pool-1.5.4.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/geotools/gt-metadata/9.5/gt-metadata-9.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/geotools/gt-opengis/9.5/gt-opengis-9.5.jar
[DEBUG]   /users/rsg/chs/.m2/repository/net/java/dev/jsr-275/jsr-275/1.0-beta-2/jsr-275-1.0-beta-2.jar
[DEBUG]   /users/rsg/chs/.m2/repository/jgridshift/jgridshift/1.0/jgridshift-1.0.jar
[DEBUG]   /users/rsg/chs/.m2/repository/hsqldb/hsqldb/1.8.0.7/hsqldb-1.8.0.7.jar
[DEBUG] provider classpath classpath:
[DEBUG]   /users/rsg/chs/.m2/repository/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar
[DEBUG]   /users/rsg/chs/.m2/repository/org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.jar

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Forking command line: /bin/sh -c cd /users/rsg/chs/Documents/SOSbuild/sos-importer/wizard && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.fc24.x86_64/jre/bin/java -jar /users/rsg/chs/Documents/SOSbuild/sos-importer/wizard/target/surefire/surefirebooter2636155203791404338.jar /users/rsg/chs/Documents/SOSbuild/sos-importer/wizard/target/surefire/surefire4366874524835169153tmp /users/rsg/chs/Documents/SOSbuild/sos-importer/wizard/target/surefire/surefire_13489146895989677212tmp

Results :

Failed tests:   shouldSetAllValuesViaSetLong(org.n52.sos.importer.feeder.model.TimestampTest): (..)

Tests run: 25, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] 52North SOS-Importer ............................... SUCCESS [  0.394 s]
[INFO] XMLbeans Module .................................... SUCCESS [ 24.367 s]
[INFO] Wizard Module ...................................... SKIPPED
[INFO] Feeding Module ..................................... FAILURE [ 21.505 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.658 s (Wall Clock)
[INFO] Finished at: 2018-03-22T09:26:25+00:00
[INFO] Final Memory: 52M/862M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "check" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project 52n-sos-importer-feeder: There are test failures.
[ERROR] 
[ERROR] Please refer to /users/rsg/chs/Documents/SOSbuild/sos-importer/feeder/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project 52n-sos-importer-feeder: There are test failures.

Please refer to /users/rsg/chs/Documents/SOSbuild/sos-importer/feeder/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /users/rsg/chs/Documents/SOSbuild/sos-importer/feeder/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:83)
	at org.apache.maven.plugin.surefire.SurefirePlugin.writeSummary(SurefirePlugin.java:176)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:150)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:650)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:586)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 11 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :52n-sos-importer-feeder

thanks
