### ISSUE TITLE
NoSuchMethodException SOS Importer Wizard Module

### ISSUE THREAD

**Issue by truptipadiya** [52North/sos-importer#99]
I am new to 52n SOS and I have installed SOS version 4.3.3. Java version is 8. I am trying to import data from example.csv file using the wizard jar file and getting the following exception:

14:09:22.076 [main] INFO  Feeder - Application started
		Implementation-Title: Feeding Module
		Implementation-Version: 0.4.1
		Archiver-Version: Plexus Archiver
		Built-By: eike
		Implementation-Vendor-Id: org.n52.sensorweb
		geotools-version: 9.5
		n52-oxf-version: 2.0.0-alpha.4
		Manifest-Version: 1.0
		Implementation-Vendor: 52°North
		Main-Class: org.n52.sos.importer.feeder.Feeder
		build-time: 2018-11-14_16-10
		Created-By: Apache Maven
		Build-Jdk: 1.8.0_181
		n52-sos-importer-xmlbeans-version: 0.2
		HeapSize Information: max: 3540MB; total now: 240MB; free now: 227MB; used now: 12MB
		os.name: Linux; os.arch: amd64; os.version: 4.15.0-39-generic
14:09:22.285 [OneTimeFeeder] INFO  OneTimeFeeder - Starting feeding data from file via configuration 'example-data.csv.52n-sos-import-config.xml' to SOS instance
14:09:22.293 [OneTimeFeeder] TRACE SensorObservationService - SensorObservationService(Configuration [file=/opt/sos-importer-master/example-data.csv.52n-sos-import-config.xml])
Exception in thread "OneTimeFeeder" java.lang.NoSuchMethodError: org.apache.http.util.VersionInfo.getUserAgent(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/String;
	at org.apache.http.impl.client.DefaultHttpClient.setDefaultHttpParams(DefaultHttpClient.java:185)
	at org.apache.http.impl.client.DefaultHttpClient.createHttpParams(DefaultHttpClient.java:160)
	at org.apache.http.impl.client.AbstractHttpClient.getParams(AbstractHttpClient.java:418)
	at org.n52.oxf.util.web.SimpleHttpClient.<init>(SimpleHttpClient.java:91)
	at org.n52.oxf.util.web.SimpleHttpClient.<init>(SimpleHttpClient.java:77)
	at org.n52.oxf.util.web.SimpleHttpClient.<init>(SimpleHttpClient.java:67)
	at org.n52.oxf.sos.adapter.SOSAdapter.<init>(SOSAdapter.java:163)
	at org.n52.oxf.sos.adapter.SOSAdapter.<init>(SOSAdapter.java:134)
	at org.n52.oxf.sos.adapter.wrapper.SosWrapperFactory.doGetCapabilities(SosWrapperFactory.java:83)
	at org.n52.oxf.sos.adapter.wrapper.SosWrapperFactory.newInstance(SosWrapperFactory.java:65)
	at org.n52.sos.importer.feeder.SensorObservationService.<init>(SensorObservationService.java:196)
	at org.n52.sos.importer.feeder.task.OneTimeFeeder.run(OneTimeFeeder.java:167)
	at java.lang.Thread.run(Thread.java:748)

Please help me insert data into SOS using a csv file.

**Comment by truptipadiya** [comment]
I downloaded the new jar file: 52n-sos-importer-wizard-0.4.2-bin.jar from https://github.com/52North/sos-importer/tree/v0.4.2. I am still facing the same issue.
